#!/usr/bin/env python3
"""Generate the fn.combi macros and their routines for a stock RV64GC host.

Two files, from the SAME recipe table the hardware decodes
(src/runtime/fun_recipe.h, generated from clash-rvfun's Core/Fun.hs):

  fun_combi.S     one macro per pattern -- the packed word and a jump
  fun_combi_rt.S  one ROUTINE per pattern, assembled once into the runtime

A combinator cell used to expand to the whole recipe inline, which is fine for
a handful of cells and ruinous for a program that carries data in its graph: a
benchmark embedding a 1500-record input file becomes 100k cons cells, and at
~35 instructions each the assembler is handed millions of instructions of
identical code.  The recipe is per-PATTERN, so it belongs in one place; only
the arity and the six selectors differ per cell, and those pack into one word.
That is exactly what the machine word encodes on the rvfun target, so the
routine decodes what the hardware decodes.

The semantics are fun_helper.c's combi case:
    bases 0..5   the spine values the word selects, counted from the top
    bases 6..14  the cells about to be allocated, hp + 4k
    bases 15     zero
    write hw_n words at hp, each clr2(bases[hw_b]) | hw_t
    memoize: the elink of bases[copy] goes to the source of the deepest
             consumed entry, ws(carity-1)
    pop carity, then push push_n entries with push_v[0] ending up on top
    hp += hw_n*4, and transfer to bases[0]

The packed word is ours, not the machine's -- it never reaches the heap -- so
it uses the layout that fits a two-instruction li: arity in bits 0-2, selector
k in bits 3+3k.
"""
import re, sys

src = open(sys.argv[1]).read()
rows = re.findall(r'/\*\s*(\d+)\s*\*/\s*\{([^}]*\{[^}]*\}[^}]*\{[^}]*\}[^}]*\{[^}]*\}[^}]*\{[^}]*\})\s*\}', src)

def nums(t):
    return [int(x) for x in re.findall(r'-?\d+', t)]

mac = ["# GENERATED by gen_combi_macros.py -- do not edit.",
       "# One macro per combinator pattern: the packed word, then the routine.",
       ""]
rt  = ["# GENERATED by gen_combi_macros.py -- do not edit.",
       "# One routine per combinator pattern; see fun_macros.S for the state.",
       "    .text", ""]

for idx, body in rows:
    f = nums(body)
    push_n, hw_n, copy = f[0], f[1], f[2]
    push_v = f[3:9]; push_s = f[9:15]; hw_b = f[15:25]; hw_t = f[25:35]

    mac.append("    .macro  fn_combi_t%s ar, s0, s1, s2, s3, s4, s5" % idx)
    mac.append("    li      t4, (\\ar)|(\\s0<<3)|(\\s1<<6)|(\\s2<<9)|(\\s3<<12)|(\\s4<<15)|(\\s5<<18)")
    mac.append("    tail    _rt_combi_t%s" % idx)
    mac.append("    .endm")
    mac.append("")

    m = rt
    m.append("    .globl  _rt_combi_t%s" % idx)
    m.append("_rt_combi_t%s:" % idx)
    m.append("    la      t0, fn_cw")
    m.append("    sw      t4, 0(t0)                # the word, across every scratch")
    m.append("    FN_GCCHECK")
    m.append("    FN_DEPTH t6")
    m.append("    la      t0, fn_cw")
    m.append("    lw      t5, 0(t0)")
    m.append("    andi    t5, t5, 7                # arity")
    m.append("    blt     t6, t5, 90f              # under-applied: NORMAL_FORM")
    # past the arity gate this IS a reduction: count it
    m.append("    la      t0, fn_reductions")
    m.append("    ld      t1, 0(t0)")
    m.append("    addi    t1, t1, 1")
    m.append("    sd      t1, 0(t0)")
    m.append("    la      t0, fn_car")
    m.append("    sw      t5, 0(t0)")
    # bases 0..5 from the spine, 0 when the selector is past the depth.
    # Only the slots this recipe actually READS are materialized: every slot
    # costs a reload of the word, a shift, a mask, a windowed read and a store,
    # and a select uses exactly one of the six.  Emitting all of them made the
    # arity-1 select routine 141 instructions.
    used = set([0])                              # bases[0] is the transfer target
    if copy < 6: used.add(copy)
    for k in range(hw_n):
        if hw_b[k] < 6: used.add(hw_b[k])
    for k in range(push_n):
        if push_v[k] < 6: used.add(push_v[k])
        if push_s[k] < 6: used.add(push_s[k])
    for k in sorted(used):
        m.append("    la      t0, fn_cw")
        m.append("    lw      t5, 0(t0)")
        m.append("    srli    t5, t5, %d" % (3 + 3 * k))
        m.append("    andi    t5, t5, 7")
        m.append("    blt     t5, t6, 1%df" % k)
        m.append("    li      t4, 0")
        m.append("    j       2%df" % k)
        m.append("1%d: FN_WVR  t4, t5" % k)
        m.append("2%d: la     t3, fn_bases" % k)
        m.append("    sd      t4, %d(t3)" % (8 * k))
    # bases 6..14 are the cells being allocated.  A cell is CODE here, and a
    # link cell is longer than a transfer cell, so the offsets come from the
    # recipe's own elink bits rather than from a fixed 4-byte stride.
    sizes = [20 for k in range(hw_n)]        # one cell size everywhere
    offs, acc = [], 0
    for z in sizes:
        offs.append(acc); acc += z
    total = acc
    m.append("    la      t0, fn_hp")
    m.append("    ld      t1, 0(t0)                # hp")
    m.append("    la      t3, fn_bases")
    for k in range(9):
        off = offs[k] if k < hw_n else total
        m.append("    addi    t4, t1, %d" % off)
        m.append("    sd      t4, %d(t3)" % (8 * (6 + k)))
    m.append("    sd      zero, %d(t3)             # base 15" % (8 * 15))
    # the cells themselves: each is the code that performs its own transfer
    for k in range(hw_n):
        m.append("    la      t3, fn_bases")
        m.append("    ld      t5, %d(t3)           # hw_b[%d]" % (8 * hw_b[k], k))
        m.append("    andi    t5, t5, -4")
        m.append("    la      t0, fn_hp")
        m.append("    ld      t1, 0(t0)")
        m.append("    addi    t6, t1, %d" % offs[k])
        if hw_t[k] & 1:
            m.append("    FN_WCELL_ELINK t6, t5")
        else:
            m.append("    FN_WCELL_LINK  t6, t5")
    # the Turner update: into the source of the deepest consumed entry
    m.append("    la      t0, fn_car")
    m.append("    lw      t5, 0(t0)")
    m.append("    beqz    t5, 30f")
    m.append("    addi    t5, t5, -1")
    m.append("    la      t0, fn_rsp")
    m.append("    lw      t2, 0(t0)")
    m.append("    sub     t2, t2, t5")
    m.append("    addi    t2, t2, -1")
    m.append("    la      t0, fn_ss")
    m.append("    slli    t5, t2, 3")
    m.append("    add     t0, t0, t5")
    m.append("    ld      t2, 0(t0)                # ws(ar-1)")
    m.append("    beqz    t2, 30f")
    m.append("    la      t3, fn_bases")
    m.append("    ld      t4, %d(t3)               # bases[copy]" % (8 * copy))
    m.append("    andi    t2, t2, -4")
    m.append("    FN_MEMO t2, t4")
    m.append("30:")
    # hp advances
    m.append("    la      t0, fn_hp")
    m.append("    ld      t1, 0(t0)")
    m.append("    addi    t1, t1, %d" % total)
    m.append("    sd      t1, 0(t0)")
    m.append("    fence.i")                        # the cells are instructions
    # the transfer target, read before the spine changes
    m.append("    la      t3, fn_bases")
    m.append("    ld      t6, 0(t3)                # target = bases[0]")
    # pop then push: push_v[0] must end up on top, so push in reverse
    m.append("    la      t0, fn_car")
    m.append("    lw      t5, 0(t0)")
    m.append("    FN_POPN_RR t5")
    for k in range(push_n - 1, -1, -1):
        m.append("    la      t3, fn_bases")
        m.append("    ld      t4, %d(t3)" % (8 * push_v[k]))
        m.append("    ld      t5, %d(t3)" % (8 * push_s[k]))
        m.append("    FN_PUSH t4, t5")
    m.append("    mv      t4, t6")
    m.append("    andi    t4, t4, -4")
    m.append("    jr      t4                       # native code: just go there")
    m.append("90: la      t4, fn_nfa")
    m.append("    ld      t4, 0(t4)")
    m.append("    jr      t4")
    m.append("")

open(sys.argv[2], "w").write("\n".join(mac) + "\n")
open(sys.argv[3], "w").write("\n".join(rt) + "\n")
print("%d patterns: %d macro lines, %d routine lines" % (len(rows), len(mac), len(rt)))
